name: build

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Build jar
        run: mvn -q -DskipTests package
      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: webhook-sql-jar
          path: target/*.jar
